# -*- coding: utf-8 -*-
"""Survey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNaVB8xYrt967eftn1O7Fec_5KariWzk
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("survey_data.csv")

# Preview dataset
print(df.head())

# Age group distribution
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Age_Group")
plt.title("Age Distribution of Respondents")
plt.show()

# Device usage
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Device_Used")
plt.title("Devices Used to Access Digital Libraries")
plt.show()

# Awareness of big data analytics
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="BigData_Awareness")
plt.title("Awareness of Big Data Analytics")
plt.show()