# -*- coding: utf-8 -*-
"""Survey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNaVB8xYrt967eftn1O7Fec_5KariWzk
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("survey_data.csv")

# Preview dataset
print("Dataset Preview:")
print(df.head())

print("\nDataset Info:")
print(df.info())

# Age distribution
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Age_Group")
plt.title("Age Distribution of Respondents")
plt.show()

# Device usage
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Device_Used")
plt.title("Devices Used to Access Digital Libraries")
plt.show()

# Awareness of Big Data Analytics
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="BigData_Awareness")
plt.title("Awareness of Big Data Analytics")
plt.show()

# Training preferences
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Training_Preference")
plt.title("Preferred Training Methods for Big Data Skills")
plt.show()